version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    networks:
      - my-network
    volumes:
      - mongodata:/my/own/datadir    

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-container
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - mongodb

networks:
  my-network:
    driver: bridge

volumes:
  mongodata:
